
title: Oliver Michel

nav:
  - text: about
    url: /
  - text: research
    url: /research/
  - text: publications
    url: /publications/

social:
  linkedin: "http://www.linkedin.com/in/olivermichel"
  google_scholar: "https://scholar.google.com/citations?view_op=list_works&hl=en&user=qWwItckAAAAJ"
  github: "http://github.com/olivermichel"
  twitter: "https://twitter.com/omichel_net"
  orcid: "https://orcid.org/0000-0002-4256-2365"

baseurl: ""
url: "https://olivermichel.github.io"

markdown: kramdown

exclude:
  - node_modules

sass:
  style: compressed
  load_paths:
    - _sass
    - vendor/foundation/scss