
title: Oliver Michel

nav:
  - text: about
    url: /
  - text: research
    url: /research/
  - text: publications
    url: /publications/
  - text: resume
    url: /resume/

social:
  linkedin: "http://www.linkedin.com/in/olivermichel"
  google_scholar: "http://scholar.google.com/citations?user=flrVM7wAAAAJ&hl=en&oi=ao"
  github: "http://github.com/olivermichel"


baseurl: ""
url: "https://olivermichel.github.io"

markdown: kramdown

exclude:
  - node_modules

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules/foundation-sites/scss